title: Deep House Online Radio | Дип хаус онлайн радио
url: https://mdeep.ru
lang: ru_RU
permalink: /:title

header_pages:
  - index.md
  - playlist.md
  - about.md
  - 320kbps.md
  - donate.md
  
sass:
  style: :compressed
  
compress_html:
  clippings: all
  comments: all
    
style: dark

footer: '<a href="https://t.me/dhtop" target="_blank" rel="noreferrer nofollow">/telegram</a> <a href="https://vk.com/deepmania" target="_blank" rel="noreferrer nofollow">/вконтакте</a> <a href="https://play.google.com/store/apps/details?id=com.mdeep.radio" target="_blank" rel="noreferrer nofollow">/google play</a>'

markdown: kramdown

plugins:
  - jekyll-sitemap
